[window]
opacity = 0.85
decorations = "none"

[window.dimensions]
columns = 140
lines = 70

[font]
size = 11.0

[font.bold]
family = "MesloLGS Nerd font"
style = "Bold"

[font.italic]
family = "MesloLGS Nerd Font"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font"
style = "Regular"

[colors.normal]
black = "0x282828"
blue = "0x458588"
cyan = "0x689d6a"
green = "0x98971a"
magenta = "0xb16286"
red = "0xcc241d"
white = "0xa89984"
yellow = "0xd79921"

[window.padding]
x = 5
y = 5

[colors.primary]
background = "0x282828"
foreground = "0xebdbb2"
